[project]
name = "pytorch-profiling"
version = "0.0.1"

# TODO min,max
dependencies = [
    "lightning",
    "torch",
    "torchvision",
    "tensorboard",
    "torch-tb-profiler",
    "jsonargparse[signatures]>=4.27.7",
    "scipy",
]

[tool.black]
line-length = 79
include = '\.pyi?$'

[tool.isort]
profile = "black"
